services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres-rails-intro
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: leopold
      POSTGRES_DB: rails
    networks:
      - rails-dev-network

networks:
  rails-dev-network:
    name: rails-dev-network